import type { BotDefinition } from "../types/index.ts"

export const BOT_DEFINITIONS: BotDefinition[] = [
  {
    userAgentPattern: "GPTBot",
    botName: "GPTBot",
    platform: "OpenAI",
    botType: "training",
    purpose: "AI Training & Search",
  },
  {
    userAgentPattern: "ChatGPT-User",
    botName: "ChatGPT-User",
    platform: "OpenAI",
    botType: "assistant",
    purpose: "Real-time browsing",
  },
  {
    userAgentPattern: "OAI-SearchBot",
    botName: "OAI-SearchBot",
    platform: "OpenAI",
    botType: "search",
    purpose: "AI search",
  },
  {
    userAgentPattern: "ClaudeBot",
    botName: "ClaudeBot",
    platform: "Anthropic",
    botType: "training",
    purpose: "AI training",
  },
  {
    userAgentPattern: "Claude-Web",
    botName: "Claude-Web",
    platform: "Anthropic",
    botType: "assistant",
    purpose: "Real-time browsing",
  },
  {
    userAgentPattern: "Google-Extended",
    botName: "Google-Extended",
    platform: "Google",
    botType: "training",
    purpose: "Gemini training",
  },
  {
    userAgentPattern: "PerplexityBot",
    botName: "PerplexityBot",
    platform: "Perplexity",
    botType: "search",
    purpose: "AI search",
  },
  {
    userAgentPattern: "Meta-ExternalAgent",
    botName: "Meta-ExternalAgent",
    platform: "Meta",
    botType: "training",
    purpose: "AI training",
  },
  {
    userAgentPattern: "Applebot-Extended",
    botName: "Applebot-Extended",
    platform: "Apple",
    botType: "training",
    purpose: "AI training",
  },
  {
    userAgentPattern: "CCBot",
    botName: "CCBot",
    platform: "Common Crawl",
    botType: "training",
    purpose: "AI training",
  },
  {
    userAgentPattern: "Bytespider",
    botName: "Bytespider",
    platform: "Bytedance",
    botType: "training",
    purpose: "AI training",
  },
];
